title: "luona.dev GPT Knowledge Base"
description: >-
  Documentation and knowledge base for the [latest]GPTs project, 
  featuring GPT models for various programming libraries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gpts.luona.dev" # the base hostname & protocol for your site

header_pages:
  - gpts/index.md
  - research/index.md


# Build settings
markdown: kramdown
remote_theme: jekyll/minima # or another theme
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  # - jekyll-feed
  # - jekyll-titles-from-headings


# Exclude from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

minima:
  skin: "dark"
  social_links:
      - { platform: twitter, user_url: "https://twitter.com/LuonaDev" }
      - { platform: github, user_url: "https://github.com/luona-dev" }


author: 
  name: luona.dev
  email: contact@luona.dev  

google_analytics: G-NXEC9DNP3M


