title: "luona.dev GPT Knowledge Base"
description: >-
  Documentation and knowledge base for the [latest]GPTs project, 
  featuring GPT models for various programming libraries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gpts.luona.dev" # the base hostname & protocol for your site

header_pages:
  - research/index.md
  - gpts/index.md
  


# Build settings
markdown: kramdown
remote_theme: jekyll/minima # or another theme
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  # - jekyll-titles-from-headings


# Exclude from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

minima:
  skin: "dark"
  social_links:
      - { platform: twitter, user_url: "https://twitter.com/LuonaDev" }
      - { platform: github, user_url: "https://github.com/luona-dev" }


author: 
  name: luona.dev
  email: contact@luona.dev  

google_analytics: G-NXEC9DNP3M


# title: "luona.dev GPT Knowledge Base"
# email: contact@luona.dev
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/
